/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.LaporanController;
import Controller.UserController;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public final class EditLaporan extends javax.swing.JFrame {
    private final int userId;

    /**
     * Creates new form MenuAdmin
     * @param userId
     */
    public EditLaporan(int userId) {
        this.userId = userId;
        initComponents();
        setLocationRelativeTo(null);
        loadLaporanData();
    }
    
    void loadLaporanData() {
        try {
            DefaultTableModel model = new DefaultTableModel();
            model.addColumn("ID Laporan");
            model.addColumn("Nama Jalan");
            model.addColumn("Kecamatan");
            model.addColumn("Tanggal Laporan");
            model.addColumn("Deskripsi");
            model.addColumn("Tingkat Kerusakan");
            model.addColumn("Status Laporan");
            tabelEdit.setModel(model);

            ArrayList<Object[]> laporanList = LaporanController.getAllLaporan();

            for (Object[] laporan : laporanList) {
                model.addRow(laporan);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan saat memuat data laporan.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelEdit = new javax.swing.JTable();
        buttonKembali = new javax.swing.JButton();
        ComboBoxStatus = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        buttonSimpan = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabelEdit.setFont(new java.awt.Font("Bahnschrift", 0, 10)); // NOI18N
        tabelEdit.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabelEdit);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 800, 330));

        buttonKembali.setBackground(new java.awt.Color(153, 0, 0));
        buttonKembali.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        buttonKembali.setForeground(new java.awt.Color(255, 255, 255));
        buttonKembali.setText("KEMBALI");
        buttonKembali.setBorder(null);
        buttonKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonKembaliActionPerformed(evt);
            }
        });
        getContentPane().add(buttonKembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 50, 90, 30));

        ComboBoxStatus.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        ComboBoxStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Belum Diproses", "Sedang Diproses", "Selesai" }));
        ComboBoxStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxStatusActionPerformed(evt);
            }
        });
        getContentPane().add(ComboBoxStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, 240, 30));

        jLabel6.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Status Laporan");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 120, 30));

        buttonSimpan.setBackground(new java.awt.Color(0, 0, 102));
        buttonSimpan.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        buttonSimpan.setForeground(new java.awt.Color(255, 255, 255));
        buttonSimpan.setText("Simpan");
        buttonSimpan.setBorder(null);
        buttonSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSimpanActionPerformed(evt);
            }
        });
        getContentPane().add(buttonSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 130, 80, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/editlaporan1 (1).png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        jButton1.setText("jButton1");
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 50, 90, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSimpanActionPerformed
    int selectedRow = tabelEdit.getSelectedRow();
    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Pilih laporan yang ingin diubah!", "Peringatan", JOptionPane.WARNING_MESSAGE);
        return;
    }

    try {
        int laporanId = (int) tabelEdit.getValueAt(selectedRow, 0);
        String statusBaru = (String) ComboBoxStatus.getSelectedItem();

        LaporanController laporanController = new LaporanController();
        boolean success = laporanController.updateStatusLaporan(laporanId, statusBaru);

        if (success) {
            JOptionPane.showMessageDialog(this, "Status laporan berhasil diperbarui!", "Sukses", JOptionPane.INFORMATION_MESSAGE);
            loadLaporanData();
        } else {
            JOptionPane.showMessageDialog(this, "Gagal memperbarui status laporan!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this, "Terjadi kesalahan saat memperbarui status laporan!", "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_buttonSimpanActionPerformed

    private void ComboBoxStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBoxStatusActionPerformed

    private void buttonKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonKembaliActionPerformed
        MenuAdmin menuAdmin = new MenuAdmin(userId);
        menuAdmin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_buttonKembaliActionPerformed
    public static void main(String[] args) {
        UserController userController = new UserController();
        java.awt.EventQueue.invokeLater(() -> {
            int userId = userController.getCurrentUserId();
            new EditLaporan(userId).setVisible(true);
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBoxStatus;
    private javax.swing.JButton buttonKembali;
    private javax.swing.JToggleButton buttonSimpan;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelEdit;
    // End of variables declaration//GEN-END:variables
}
