/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.LaporanController;
import Controller.UserController;
import Model.Pelapor;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author ASUS
 */
public final class LihatLaporanPelapor extends javax.swing.JFrame {
    private UserController userController;
    private int userId;


    public LihatLaporanPelapor(int userId) {
        initComponents();
        setLocationRelativeTo(null);
        tampilkanLaporanPelapor();
    }

    void tampilkanLaporanPelapor() {
        try {
            DefaultTableModel model = new DefaultTableModel();
            model.addColumn("ID Laporan");
            model.addColumn("Nama Jalan");
            model.addColumn("Kecamatan");
            model.addColumn("Tanggal Laporan");
            model.addColumn("Deskripsi");
            model.addColumn("Tingkat Kerusakan");
            model.addColumn("Status Laporan");
            tabelLaporan.setModel(model);

            Pelapor pelapor = new Pelapor("username", "password", "namaLengkap", "noTelp", "email");
            ArrayList<Object[]> laporanList = pelapor.viewData();

            for (Object[] laporan : laporanList) {
                model.addRow(laporan);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan saat memuat data laporan!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    void filterLaporanKerusakan(String tingkatKerusakan) {
        try {
            DefaultTableModel model = new DefaultTableModel();
            model.addColumn("ID Laporan");
            model.addColumn("Nama Jalan");
            model.addColumn("Kecamatan");
            model.addColumn("Tanggal Laporan");
            model.addColumn("Deskripsi");
            model.addColumn("Tingkat Kerusakan");
            model.addColumn("Status Laporan");
            tabelLaporan.setModel(model);

            ArrayList<Object[]> laporanList = LaporanController.filterLaporanKerusakan(tingkatKerusakan);
            if (laporanList != null) {
                for (Object[] laporan : laporanList) {
                    model.addRow(laporan);
                }
            }
        } catch (SQLException ex) {
                Logger.getLogger(LihatLaporanPelapor.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this, "Terjadi kesalahan saat mencari data laporan!", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tabelLaporan = new javax.swing.JTable();
        buttonFilter = new javax.swing.JToggleButton();
        buttonKembali = new javax.swing.JButton();
        buttonCari = new javax.swing.JToggleButton();
        cariField = new javax.swing.JTextField();
        ComboBoxTingkatKerusakan = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 500));
        setSize(new java.awt.Dimension(800, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabelLaporan.setFont(new java.awt.Font("Bahnschrift", 0, 10)); // NOI18N
        tabelLaporan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tabelLaporan);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 207, 800, 300));

        buttonFilter.setBackground(new java.awt.Color(0, 0, 102));
        buttonFilter.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        buttonFilter.setForeground(new java.awt.Color(255, 255, 255));
        buttonFilter.setText("Filter");
        buttonFilter.setBorder(null);
        buttonFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonFilterActionPerformed(evt);
            }
        });
        getContentPane().add(buttonFilter, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 90, 30));

        buttonKembali.setBackground(new java.awt.Color(153, 0, 0));
        buttonKembali.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        buttonKembali.setForeground(new java.awt.Color(255, 255, 255));
        buttonKembali.setText("KEMBALI");
        buttonKembali.setBorder(null);
        buttonKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonKembaliActionPerformed(evt);
            }
        });
        getContentPane().add(buttonKembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 50, 90, 30));

        buttonCari.setBackground(new java.awt.Color(0, 0, 102));
        buttonCari.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        buttonCari.setForeground(new java.awt.Color(255, 255, 255));
        buttonCari.setText("Cari");
        buttonCari.setBorder(null);
        buttonCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCariActionPerformed(evt);
            }
        });
        getContentPane().add(buttonCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 140, 60, 30));

        cariField.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        getContentPane().add(cariField, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 140, 260, 30));

        ComboBoxTingkatKerusakan.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        ComboBoxTingkatKerusakan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rusak Ringan", "Rusak Sedang", "Rusak Berat", "Semua" }));
        ComboBoxTingkatKerusakan.setBorder(null);
        ComboBoxTingkatKerusakan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxTingkatKerusakanActionPerformed(evt);
            }
        });
        getContentPane().add(ComboBoxTingkatKerusakan, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, 140, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/lihatlaporan1.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setMaximumSize(new java.awt.Dimension(800, 500));
        jLabel1.setMinimumSize(new java.awt.Dimension(800, 500));
        jLabel1.setPreferredSize(new java.awt.Dimension(800, 500));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ComboBoxTingkatKerusakanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxTingkatKerusakanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBoxTingkatKerusakanActionPerformed

    private void buttonKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonKembaliActionPerformed
        MenuUser menuUser = new MenuUser(userId);
        menuUser.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_buttonKembaliActionPerformed

    private void buttonCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCariActionPerformed
        String namaJalan = cariField.getText();

        if (namaJalan.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Masukkan nama jalan untuk mencari laporan!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            DefaultTableModel model = new DefaultTableModel();
            model.addColumn("ID Laporan");
            model.addColumn("Nama Jalan");
            model.addColumn("Kecamatan");
            model.addColumn("Tanggal Laporan");
            model.addColumn("Deskripsi");
            model.addColumn("Tingkat Kerusakan");
            model.addColumn("Status Laporan");
            tabelLaporan.setModel(model);

            ArrayList<Object[]> laporanList = LaporanController.cariJalanPelapor(namaJalan);

            for (Object[] laporan : laporanList) {
                model.addRow(laporan);
            }

            if (laporanList.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Tidak ada laporan ditemukan untuk nama jalan: " + namaJalan, "Info", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan saat mencari laporan!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_buttonCariActionPerformed

    private void buttonFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonFilterActionPerformed
        String tingkatKerusakan = (String) ComboBoxTingkatKerusakan.getSelectedItem();
        filterLaporanKerusakan(tingkatKerusakan); 
    }//GEN-LAST:event_buttonFilterActionPerformed
    public static void main(String[] args) {
        UserController userController = new UserController();
        java.awt.EventQueue.invokeLater(() -> {
            int userId = userController.getCurrentUserId();
            new LihatLaporanPelapor(userId).setVisible(true);
        });
    }

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBoxTingkatKerusakan;
    private javax.swing.JToggleButton buttonCari;
    private javax.swing.JToggleButton buttonFilter;
    private javax.swing.JButton buttonKembali;
    private javax.swing.JTextField cariField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabelLaporan;
    // End of variables declaration//GEN-END:variables
}
