/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.LaporanController;
import Controller.UserController;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class MenuLapor extends javax.swing.JFrame {
    private final LaporanController laporanController;
    private final int userId;

    public MenuLapor(int userId) {
        initComponents();
        setLocationRelativeTo(null); 
        laporanController = new LaporanController();
        this.userId = userId;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonKembali = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        deskripsiField = new javax.swing.JTextField();
        comboBoxKerusakan = new javax.swing.JComboBox<>();
        buttonKirim = new javax.swing.JToggleButton();
        jLabel3 = new javax.swing.JLabel();
        kecamatanField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        namaJalanField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(800, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonKembali.setBackground(new java.awt.Color(153, 0, 0));
        buttonKembali.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        buttonKembali.setForeground(new java.awt.Color(255, 255, 255));
        buttonKembali.setText("KEMBALI");
        buttonKembali.setBorder(null);
        buttonKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonKembaliActionPerformed(evt);
            }
        });
        getContentPane().add(buttonKembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 50, 90, 30));

        jLabel7.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        jLabel7.setText("Deskripsi");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, 110, 30));

        deskripsiField.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        deskripsiField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deskripsiFieldActionPerformed(evt);
            }
        });
        getContentPane().add(deskripsiField, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 280, 310, 80));

        comboBoxKerusakan.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        comboBoxKerusakan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rusak Ringan", "Rusak Sedang", "Rusak Berat" }));
        comboBoxKerusakan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 2));
        getContentPane().add(comboBoxKerusakan, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 230, 310, 30));

        buttonKirim.setBackground(new java.awt.Color(204, 0, 0));
        buttonKirim.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        buttonKirim.setForeground(new java.awt.Color(255, 255, 255));
        buttonKirim.setText("KIRIM");
        buttonKirim.setBorder(null);
        buttonKirim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonKirimActionPerformed(evt);
            }
        });
        getContentPane().add(buttonKirim, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 390, 90, 30));

        jLabel3.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        jLabel3.setText("Tingkat Kerusakan");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, -1, 40));

        kecamatanField.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        getContentPane().add(kecamatanField, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, 310, 30));

        jLabel2.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        jLabel2.setText("Kecamatan");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 80, 40));

        jLabel1.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        jLabel1.setText("Nama Jalan ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 100, 30));

        namaJalanField.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        namaJalanField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaJalanFieldActionPerformed(evt);
            }
        });
        getContentPane().add(namaJalanField, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 130, 310, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/buatlaporan1.png"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        jButton1.setText("jButton1");
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 50, 90, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void namaJalanFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaJalanFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaJalanFieldActionPerformed

    private void buttonKirimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonKirimActionPerformed
        String namaJalan = namaJalanField.getText().trim();
        String kecamatan = kecamatanField.getText().trim();
        String tingkatKerusakan = comboBoxKerusakan.getSelectedItem().toString().trim();
        String deskripsi = deskripsiField.getText().trim();

        if (namaJalan.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Nama jalan tidak boleh kosong!");
            namaJalanField.requestFocus();
            return;
        }

        if (kecamatan.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Kecamatan tidak boleh kosong!");
            kecamatanField.requestFocus();
            return;
        }

        if (tingkatKerusakan.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Tingkat kerusakan harus dipilih!");
            comboBoxKerusakan.requestFocus();
            return;
        }

        if (deskripsi.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Deskripsi tidak boleh kosong!");
            deskripsiField.requestFocus();
            return;
        }

        boolean berhasil = laporanController.simpanLaporan(namaJalan, kecamatan, deskripsi, tingkatKerusakan, userId);

        if (berhasil) {
            JOptionPane.showMessageDialog(null, "Laporan berhasil ditambahkan");
            namaJalanField.setText("");
            kecamatanField.setText("");
            comboBoxKerusakan.setSelectedIndex(0);
            deskripsiField.setText("");

            MenuUser menuUser = new MenuUser(userId);
            menuUser.setVisible(true);
            this.dispose();

        } else {
            JOptionPane.showMessageDialog(null, "Gagal menambahkan laporan");
        }
    }//GEN-LAST:event_buttonKirimActionPerformed

    private void deskripsiFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deskripsiFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deskripsiFieldActionPerformed

    private void buttonKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonKembaliActionPerformed
        MenuUser menuUser = new MenuUser(userId);
        menuUser.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_buttonKembaliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        UserController usercontroller = new UserController();
//        usercontroller.loginUser("testuser", "testpassword");
        int userId = usercontroller.getCurrentUserId();
        System.out.println("User ID diambil dari UserController: " + userId);

        java.awt.EventQueue.invokeLater(() -> {
            new MenuLapor(userId).setVisible(true);
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonKembali;
    private javax.swing.JToggleButton buttonKirim;
    private javax.swing.JComboBox<String> comboBoxKerusakan;
    private javax.swing.JTextField deskripsiField;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField kecamatanField;
    private javax.swing.JTextField namaJalanField;
    // End of variables declaration//GEN-END:variables
}
