/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author ASUS
 */
public class MenuUser extends javax.swing.JFrame {
    private static int userId;

    /**
     * Creates new form MenuUser
     * @param userId
     */
    public MenuUser(int userId) {
        initComponents();
        setLocationRelativeTo(null);
        this.userId = userId;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonkembali = new javax.swing.JButton();
        buttonlihat = new javax.swing.JButton();
        buttonlapor = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 500));
        setSize(new java.awt.Dimension(800, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonkembali.setBackground(new java.awt.Color(153, 0, 0));
        buttonkembali.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        buttonkembali.setForeground(new java.awt.Color(255, 255, 255));
        buttonkembali.setText("KEMBALI");
        buttonkembali.setBorder(null);
        buttonkembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonkembaliActionPerformed(evt);
            }
        });
        getContentPane().add(buttonkembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 50, 90, 30));

        buttonlihat.setBackground(new java.awt.Color(204, 0, 0));
        buttonlihat.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        buttonlihat.setForeground(new java.awt.Color(255, 255, 255));
        buttonlihat.setText("LIHAT LAPORAN");
        buttonlihat.setBorder(null);
        buttonlihat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonlihatActionPerformed(evt);
            }
        });
        getContentPane().add(buttonlihat, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 230, 220, 190));

        buttonlapor.setBackground(new java.awt.Color(204, 0, 0));
        buttonlapor.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        buttonlapor.setForeground(new java.awt.Color(255, 255, 255));
        buttonlapor.setText("BUAT LAPORAN");
        buttonlapor.setActionCommand("BUAT\n");
        buttonlapor.setBorder(null);
        buttonlapor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonlaporActionPerformed(evt);
            }
        });
        getContentPane().add(buttonlapor, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 220, 190));

        jLabel4.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("partisipasi dalam menyampaikan pengaduan mengenai jalan yang mengalami kerusakan");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, -1, -1));

        jLabel3.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText(" jalan rusak di kota Samarinda. LAPORJALAN memberikan kemudahan kepada warga kota Samarinda untuk ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 155, -1, 10));

        jLabel2.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel2.setText("Layanan Pelaporan Jalan Rusak  (LAPORJALAN) adalah sebuah layanan penyampaian laporan dan pengaduan");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, -1, 50));
        jLabel2.getAccessibleContext().setAccessibleName("Layanan Pelaporan Jalan Rusak  (LAPORJALAN) adalah sebuah layanan penyampaian laporan dan pengaduan\n jalan rusak di kota Samarinda. LAPORJALAN memberikan kemudahan kepada warga kota Samarinda untuk \npartisipasi dalam menyampaikan pengaduan mengenai jalan yang mengalami kerusakan");
        jLabel2.getAccessibleContext().setAccessibleDescription("");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/menuuser (1).png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        jButton3.setText("jButton3");
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 50, 90, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonlaporActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonlaporActionPerformed
        MenuLapor menuLapor = new MenuLapor(userId);
        menuLapor.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_buttonlaporActionPerformed

    private void buttonkembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonkembaliActionPerformed
        Login login = new Login();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_buttonkembaliActionPerformed

    private void buttonlihatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonlihatActionPerformed
        LihatLaporanPelapor lihatLaporan = new LihatLaporanPelapor(userId);
        lihatLaporan.setVisible(true);
        lihatLaporan.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_buttonlihatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MenuUser(userId).setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonkembali;
    private javax.swing.JButton buttonlapor;
    private javax.swing.JButton buttonlihat;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
