/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.LaporanController;

/**
 *
 * @author ASUS
 */
public class MenuAdmin extends javax.swing.JFrame {
    private final LaporanController laporanController;
    private static int userId;
    /**
     * Creates new form MenuAAdmin
     * @param userId
     */
    public MenuAdmin(int userId) {
        initComponents();
        setLocationRelativeTo(null); 
        laporanController = new LaporanController();
        this.userId = userId;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonKembali = new javax.swing.JToggleButton();
        buttonlihat = new javax.swing.JButton();
        buttonedit = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(800, 500));
        setMinimumSize(new java.awt.Dimension(800, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonKembali.setBackground(new java.awt.Color(153, 0, 0));
        buttonKembali.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        buttonKembali.setForeground(new java.awt.Color(255, 255, 255));
        buttonKembali.setText("KEMBALI");
        buttonKembali.setBorder(null);
        buttonKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonKembaliActionPerformed(evt);
            }
        });
        getContentPane().add(buttonKembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 50, 90, 30));

        buttonlihat.setBackground(new java.awt.Color(204, 0, 0));
        buttonlihat.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        buttonlihat.setForeground(new java.awt.Color(255, 255, 255));
        buttonlihat.setText("LIHAT LAPORAN");
        buttonlihat.setBorder(null);
        buttonlihat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonlihatActionPerformed(evt);
            }
        });
        getContentPane().add(buttonlihat, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 220, 220, 200));

        buttonedit.setBackground(new java.awt.Color(204, 0, 0));
        buttonedit.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        buttonedit.setForeground(new java.awt.Color(255, 255, 255));
        buttonedit.setText("UBAH STATUS LAPORAN");
        buttonedit.setBorder(null);
        buttonedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttoneditActionPerformed(evt);
            }
        });
        getContentPane().add(buttonedit, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 220, 200));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/user homepage.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttoneditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttoneditActionPerformed
        EditLaporan editLaporan = new EditLaporan(userId);
        editLaporan.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_buttoneditActionPerformed

    private void buttonlihatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonlihatActionPerformed
        LihatLaporanAdmin lihatLaporanAdmin = new LihatLaporanAdmin(userId);
        lihatLaporanAdmin.setVisible(true);
        lihatLaporanAdmin.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_buttonlihatActionPerformed

    private void buttonKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonKembaliActionPerformed
        Login login = new Login();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_buttonKembaliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MenuAdmin(userId).setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton buttonKembali;
    private javax.swing.JButton buttonedit;
    private javax.swing.JButton buttonlihat;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
